local M = {}
M.WINDOW_RESIZED = "WINDOW_RESIZED"
M.STORAGE_CHANGED = "STORAGE_CHANGED"
M.STORAGE_SAVED = "STORAGE_SAVED"
M.JSTODEF = "JSTODEF"
M.NEAR = "NEAR"
M.LEVEL_COMPLETED = "LEVEL_COMPLETED"
M.GAME_LIST_CHANGED = "GAME_LIST_CHANGED"
M.GAME_ACTIVE_LIST_CHANGED = "GAME_ACTIVE_LIST_CHANGED"


return M